# This is a basic workflow to help you get started with Actions

name: Pull Request

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  pull_request:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
    - name: Accéder au code du dépôt
      uses: actions/checkout@v3
      # Cette étape utilise l'action "actions/checkout" pour accéder au code du dépôt sur lequel le travail est déclenché

    - name: Installer Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
      # Cette étape utilise l'action "actions/setup-python" pour installer la version spécifiée de Python sur l'environnement de travail

    - name: Exécuter le script Python
      run: python main.py
      # Cette étape exécute le script Python "main.py"
      # Runs a single command using the runners shell

