name: pull request

on:
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  pullevent:
    runs-on: ubuntu-latest

    steps:
      # checkout the repository to access it from the code
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - run: python main.py
